

PLATITUDES = [
    'Be patient when becoming someone you haven\'t been before',
    'No one will give you the ideas you need to overthrow them',
    'You can do anything...but not everything',
    'I\'m not where I want to be, but I\'m proud I\'m not where I used to be',
    'There\'s no such thing as a victim mindset',
    'It\'s never too late to upend your whole life and start over',
    'The only person who thinks a beginner is a fool...is a beginner',
    'The easiest way to solve any problem, is to change your thinking',
    'The only person you can change is yourself',
    'Everything can be done with a bigger group of smaller tasks',
    'Impossible is just a word, not a real thing',
    'In every life you find some trouble, but when you worry you make it double',
    'The world "belief", describes your motivations',
    'It\'s okay to say no',
    'What if you just start, and then keep going for a while?',
    'All of our pasts are dead, and our minds are full of the footprints they left while passing by',
    'Empathy without boundaries is self-destruction',
    'We only die once, but we live every single day',
    'Just think of it as an experiment',
    'None of the haters are happy',
    'I\'m so lucky to know myself--I like all of the things that I like!'
    'Being silly is nice',
    'Only respecting women you\'re attracted to isn\'t respecting women',
    'It\'s okay to be happy for no reason',
    'Being a good friend is one of the best things in life',
    'I\'m becoming who I want to be today',
    'I\'m so glad I have feelings',
    'You need more things to be sad than to be happy',
    'Even if there\'s no god and no afterlife, I\'m just happy that I\'m alive right now',
    'One day, we\'ll talk to each other for the last time.  But no matter when that happens, I hope every day is the best day of your life',
    'It\'s good for people to change and grow',
    'It\'s okay to be different from other people.  We can still be in a community.',
    'If you see injustice and stay out of it, then you\'re on the bully\'s team',
    'Wouldn\'t it be great to be a snail? They\'re so fast'
    'I can\'t feel any of your feelings, no matter what',
    'Two things every person needs, are: patience, and emotional maturity',
    'People with rage are really people with grief',
    'Honestly, leaving social media has been really nice for me',
    'Any society that doesn\'t feed the hungry, give shelter to the unhoused, and medicine to the sick, and education to everyone, doesn\'t deserve to exist',
    'Anyone can have a philosophy.  Living your life well is what really matters.',
    'Don\'t live in an unlocked cage',
    'Some days, you just need to be extra',
    'Being yourself is the best part of being alive',
    'Kindness and weakness are opposites of each other',
    'If the punishment is a fine, then it\'s only a law for poor people',
    'How can you explain something you don\'t understand?'
    'I like meeting people who are different than me',
    'There\'s always enough to share',
    'I don\'t always tell people when I think they\'re wrong.',
    'We\'re all just trying to figure out life as we go',
    'It\'s always okay to hit a Nazi',
    'We\'re all guilty of the good we chose not to do',
    'Anyone can run like a girl if they\'re fast enough',
    'People decide their habits, and their habits decide their future',
    'If someone treats you like you\'re not their equal, it\'s because they are cruel, not because they are right',
    'To break a pattern, you must do a different thing',
    'You can live a full live, even if you never have kids',
    'You can live a full live, even if you never get married',
    'You can live a full live, even if you never have sex',
    'You can live a full live, even if you never take drugs',
    'Batteries that are only positive don\'t work',
    'Being polite makes hard conversations easier',
    'We\'ll never know exactly how many people are sleeping naked',
    'They say: when you die, it\'s like taking the best nap and you never have to wake up to do work again',
    'It\'s easy to forget suffering when it ends',
    'When your mind is your weapon, you can never be disarmed',
    'It\'s okay if you don\'t trust God.  God doesn\'t answer questions or explain themself.',
    'People who live out in the country side are intelligent and good people',

]



